name: Generate NBC News EPG

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  generate-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set executable permission for script
        run: chmod +x epg_generator.sh

      - name: Run EPG generator
        run: ./epg_generator.sh

      - name: Upload NBC News EPG
        uses: actions/upload-artifact@v4
        with:
          name: nbc-news-epg
          path: NBC_News.xml
